from common import *

x = np.arange(-5.0, 5.0, 0.1)
y1 = step(x)
y2 = sigmoid(x)
y3 = relu(x)
#plt.plot(x, y1, label='step', linestyle='--')
#plt.plot(x, y2, label='sigmoid')
#plt.title('step & sigmoid')
plt.plot(x, y3, label='relu')
plt.title('relu')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
#plt.ylim(-0.1, )
plt.show()
